{% set version = "0.27.0" %}

package:
  name: sqlalchemy-oso
  version: {{ version }}

source:
  url: https://github.com/osohq/oso/archive/refs/tags/sqlalchemy-v{{ version }}.tar.gz
  sha256: f97cbdf78323d6f97103e563cacc2131e77862dd250f97389f9c19acf3672eed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install languages/python/sqlalchemy-oso -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - packaging >=21.3,<24.0
    - oso =={{ version }}.*
    - sqlalchemy >=1.3.17,<1.5

test:
  source_files:
    - languages/python/sqlalchemy-oso/tests
  imports:
    - sqlalchemy_oso
  commands:
    - pip check
    - mypy -p sqlalchemy_oso --ignore-missing-imports
    - cd languages/python/sqlalchemy-oso
    - pytest -vv tests --cov=sqlalchemy_oso --no-cov-on-fail --cov-report=term-missing:skip-covered --cov-fail-under=81
  requires:
    - mypy
    - pip
    - pytest-cov
    - flask-sqlalchemy <3
    # fails pip check: https://github.com/conda-forge/importlib_metadata-feedstock/issues/88
    - importlib-metadata !=4.7.1

about:
  home: https://github.com/osohq/oso/tree/main/languages/python/sqlalchemy-oso
  summary: sqlalchemy-oso the SqlAlchemy integration for oso, the batteries-included framework for building authorization in your application.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.osohq.com/python/reference/api/sqlalchemy.html
  dev_url: https://github.com/osohq/oso

extra:
  recipe-maintainers:
    - alexpilot11
    - bollwyvl
