{% set version = "0.27.2" %}

package:
  name: sqlalchemy-oso
  version: {{ version }}

source:
  url: https://github.com/osohq/oso/archive/refs/tags/sqlalchemy-v{{ version }}.tar.gz
  sha256: 18708bfd5cb74efc04d7191ea4247cec0182a52169da511f8059861c58116f20

build:
  noarch: python
  script:
    - cd languages/python/sqlalchemy-oso && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolaiton
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - oso >=0.27.0,<0.28.0
    - packaging >=21.3,<24.0
    - python >=3.7
    - sqlalchemy >=1.3.17,<3.0

test:
  source_files:
    - languages/python/sqlalchemy-oso/tests
  imports:
    - sqlalchemy_oso
  commands:
    - pip check
    - mypy -p sqlalchemy_oso --ignore-missing-imports
    - cd languages/python/sqlalchemy-oso
    - coverage run --source sqlalchemy_oso --branch -m pytest tests --tb=long --color=yess
    - coverage report --show-missing --skip-covered --fail-under=81
  requires:
    - mypy
    - pip
    - pytest-cov
    - flask <2.2
    - flask-sqlalchemy <3.0
    # fails pip check: https://github.com/conda-forge/importlib_metadata-feedstock/issues/88
    - importlib-metadata !=4.7.1

about:
  home: https://github.com/osohq/oso/tree/main/languages/python/sqlalchemy-oso
  summary: sqlalchemy-oso the SqlAlchemy integration for oso, the batteries-included framework for building authorization in your application.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.osohq.com/python/reference/api/sqlalchemy.html
  dev_url: https://github.com/osohq/oso

extra:
  recipe-maintainers:
    - alexpilot11
    - bollwyvl
