{% set version = "0.27.2" %}

package:
  name: sqlalchemy-oso
  version: {{ version }}

source:
  url: https://github.com/osohq/oso/archive/refs/tags/sqlalchemy-v{{ version }}.tar.gz
  sha256: 18708bfd5cb74efc04d7191ea4247cec0182a52169da511f8059861c58116f20

build:
  noarch: python
  script:
    - cd languages/python/sqlalchemy-oso && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - oso >=0.27.0,<0.28.0
    - packaging >=21.3,<24.0
    - python >={{ python_min }}
    - sqlalchemy >=1.3.17,<3.0

test:
  source_files:
    - languages/python/sqlalchemy-oso/tests
  imports:
    - sqlalchemy_oso
  commands:
    - pip check
    - cd languages/python/sqlalchemy-oso
    - coverage run --source sqlalchemy_oso --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=75
  requires:
    - flask <2.2
    - flask-sqlalchemy <3.0
    - pip
    - pytest-cov
    - werkzeug ==2.2.2
    - python {{ python_min }}

about:
  home: https://github.com/osohq/oso/tree/main/languages/python/sqlalchemy-oso
  summary: sqlalchemy-oso the SqlAlchemy integration for oso, the batteries-included framework for building authorization in your application.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.osohq.com/python/reference/api/sqlalchemy.html
  dev_url: https://github.com/osohq/oso

extra:
  recipe-maintainers:
    - alexpilot11
    - bollwyvl
